# Generated by Django 5.2.1 on 2025-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('clients_on_server', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'servers',
                'managed': False,
            },
        ),
    ]
