name: Deploy to server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 91.84.111.102 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -t -i ~/.ssh/id_ed25519 root@91.84.111.102  << 'EOF'
            if ! command -v docker &> /dev/null; then
              apt update
              apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
              echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
              apt update
              apt install -y docker-ce docker-ce-cli containerd.io
            fi

            if [ ! -d "/root/vpn_adminka" ]; then
              git clone https://github.com/niccneimi/vpn_adminka.git /root/vpn_adminka
            fi

            cd /root/vpn_adminka
            git reset --hard
            git pull origin main

            if [ "$(docker ps -a -q -f name=vpn_adminka)" ]; then
              docker stop vpn_adminka || true
              docker rm vpn_adminka || true
            fi

            docker build -t vpn_adminka .
            docker run -d -p 1234:1234 --name vpn_adminka --env-file /root/.env vpn_adminka
          EOF
